//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CTMEntities : DbContext
    {
        public CTMEntities()
            : base("name=CTMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PatientDetail> PatientDetails { get; set; }
        public virtual DbSet<ReferalApointment> ReferalApointments { get; set; }
        public virtual DbSet<ReferalPreQualificationDetail> ReferalPreQualificationDetails { get; set; }
        public virtual DbSet<ReferalStatu> ReferalStatus { get; set; }
        public virtual DbSet<SiteEventDetail> SiteEventDetails { get; set; }
        public virtual DbSet<SiteEventType> SiteEventTypes { get; set; }
        public virtual DbSet<SiteReferalStatusReason> SiteReferalStatusReasons { get; set; }
        public virtual DbSet<Study> Studies { get; set; }
        public virtual DbSet<StudyProtocol> StudyProtocols { get; set; }
        public virtual DbSet<StudySiteReferalMapping> StudySiteReferalMappings { get; set; }
        public virtual DbSet<StudyStatu> StudyStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<PatientReferalMapping> PatientReferalMappings { get; set; }
    
        public virtual ObjectResult<sp_site_GetStudiesBySiteId_Result> sp_site_GetStudiesBySiteId(Nullable<int> siteID, string search, Nullable<long> fromRecord, Nullable<long> toRecord)
        {
            var siteIDParameter = siteID.HasValue ?
                new ObjectParameter("SiteID", siteID) :
                new ObjectParameter("SiteID", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var fromRecordParameter = fromRecord.HasValue ?
                new ObjectParameter("FromRecord", fromRecord) :
                new ObjectParameter("FromRecord", typeof(long));
    
            var toRecordParameter = toRecord.HasValue ?
                new ObjectParameter("ToRecord", toRecord) :
                new ObjectParameter("ToRecord", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_site_GetStudiesBySiteId_Result>("sp_site_GetStudiesBySiteId", siteIDParameter, searchParameter, fromRecordParameter, toRecordParameter);
        }
    
        public virtual ObjectResult<sp_site_GetReferalsByStudyId_Result> sp_site_GetReferalsByStudyId(Nullable<int> siteId, Nullable<int> studyId, string search, Nullable<long> fromRecord, Nullable<long> toRecord)
        {
            var siteIdParameter = siteId.HasValue ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(int));
    
            var studyIdParameter = studyId.HasValue ?
                new ObjectParameter("StudyId", studyId) :
                new ObjectParameter("StudyId", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var fromRecordParameter = fromRecord.HasValue ?
                new ObjectParameter("FromRecord", fromRecord) :
                new ObjectParameter("FromRecord", typeof(long));
    
            var toRecordParameter = toRecord.HasValue ?
                new ObjectParameter("ToRecord", toRecord) :
                new ObjectParameter("ToRecord", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_site_GetReferalsByStudyId_Result>("sp_site_GetReferalsByStudyId", siteIdParameter, studyIdParameter, searchParameter, fromRecordParameter, toRecordParameter);
        }
    }
}
