//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientReferalMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientReferalMapping()
        {
            this.ReferalPreQualificationDetails = new HashSet<ReferalPreQualificationDetail>();
            this.SiteEventDetails = new HashSet<SiteEventDetail>();
            this.ReferalApointments = new HashSet<ReferalApointment>();
        }
    
        public int ReferalId { get; set; }
        public string ReferalCode { get; set; }
        public Nullable<int> StudyId { get; set; }
        public Nullable<int> PatientId { get; set; }
    
        public virtual PatientDetail PatientDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferalPreQualificationDetail> ReferalPreQualificationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteEventDetail> SiteEventDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferalApointment> ReferalApointments { get; set; }
    }
}
