//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendSmsOrEmail
    {
        public int Id { get; set; }
        public string MessageReciver { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<int> MessgeType { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public string MessageContent { get; set; }
        public string AttachementPath { get; set; }
        public Nullable<bool> isMessagesent { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
