//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyProtocol
    {
        public int Id { get; set; }
        public string ProtocolText { get; set; }
        public Nullable<int> StudyId { get; set; }
    
        public virtual Study Study { get; set; }
    }
}
